# config for yml
source              : .
destination         : ../blog
title               : Anh Le Blog
description         : A software developer's blog about anything and everything
version             : 0.1
baseurl             : /blog/
posturlbase         : /blog
plugins             :
  - jekyll-seo-tag