# config for yml
source              : .
destination         : ../blog
title               : Anh Le
description         : A software developer's blog about anything and everything
version             : 0.1
baseurl             : /blog/
posturlbase         : /blog
plugins             :
  - jekyll-seo-tag
social              :
  name: Anh Le
  links:
    - https://www.linkedin.com/in/anhvietle/
    - https://github.com/haizzz/