# config for yml
destination         : ./posts
title               : Anh
description         : I wanted to rule the world when I was younger. But first, I'll write a blog
version             : 0.1
baseurl             : /blog/posts/